name: check-expiration
run-name: Check certificate (file) expiration

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      max_days:
        required: true
        type: number
        default: 30
    outputs:
      has_expired:
        description: "Will be equal to 'yes' if certificate has expired, otherwise 'no'"
        value: ${{ jobs.check-expiration.outputs.has_expired }}
      expire_date:
        description: "Certificate expiration date"
        value: ${{ jobs.check-expiration.outputs.expire_date }}

jobs:
  check-expiration:
    runs-on: ubuntu-latest
    outputs:
      has_expired: ${{ steps.check_exp.outputs.has_expired }}
      expire_date: ${{ steps.check_exp.outputs.expire_date }}
    steps:
      - name: Check expiration
        id: check_exp
        run: >-
          SECONDS=$(( ${{ inputs.max_days }}} * 86400))
          EXPIRATION=$(openssl x509 -noout -checkend ${SECONDS} -in ${{ inputs.file }})
          EXPIRED="no"
          if [[ ${EXPIRATION} !~ "not expire" ]]; then
            echo "Certificate is outside expiration bounds or has expired"
            EXPIRED=yes
            echo "has_expired=${EXPIRED}" >> $GITHUB_OUTPUT
          fi;
          EXP_DATE=$(openssl x509 -noout -enddate -in ${{ inputs.file }})
          echo "Certificate expiration date: ${EXP_DATE}"
          echo "expire_date=${EXP_DATE}" >> $GITHUB_OUTPUT
      - name: Finish
        run: echo "Finished.."