name: cert-req-build-ghcr
run-name: Build cert-req Docker image for the GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'server.cnf'
      - 'scripts/**'

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Europe/Athens'
      - name: Get date
        id: date
        run: echo "push_date=$(date '+%H:%M@%d/%m/%Y')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/gunet/cert-req:latest
          labels: gr.gunet.cert-req.pushdate=${{ steps.date.outputs.push_date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max